/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTruckEntryIndexRouteImport } from './routes/_app/truck-entry/index'
import { Route as AppSalesIndexRouteImport } from './routes/_app/sales/index'
import { Route as AppTruckEntryNewRouteImport } from './routes/_app/truck-entry/new'
import { Route as AppSalesNewRouteImport } from './routes/_app/sales/new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTruckEntryIndexRoute = AppTruckEntryIndexRouteImport.update({
  id: '/truck-entry/',
  path: '/truck-entry/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTruckEntryNewRoute = AppTruckEntryNewRouteImport.update({
  id: '/truck-entry/new',
  path: '/truck-entry/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSalesNewRoute = AppSalesNewRouteImport.update({
  id: '/sales/new',
  path: '/sales/new',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/sales/new': typeof AppSalesNewRoute
  '/truck-entry/new': typeof AppTruckEntryNewRoute
  '/sales/': typeof AppSalesIndexRoute
  '/truck-entry/': typeof AppTruckEntryIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/sales/new': typeof AppSalesNewRoute
  '/truck-entry/new': typeof AppTruckEntryNewRoute
  '/sales': typeof AppSalesIndexRoute
  '/truck-entry': typeof AppTruckEntryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/sales/new': typeof AppSalesNewRoute
  '/_app/truck-entry/new': typeof AppTruckEntryNewRoute
  '/_app/sales/': typeof AppSalesIndexRoute
  '/_app/truck-entry/': typeof AppTruckEntryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sales/new'
    | '/truck-entry/new'
    | '/sales/'
    | '/truck-entry/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/sales/new'
    | '/truck-entry/new'
    | '/sales'
    | '/truck-entry'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/'
    | '/_app/sales/new'
    | '/_app/truck-entry/new'
    | '/_app/sales/'
    | '/_app/truck-entry/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/truck-entry/': {
      id: '/_app/truck-entry/'
      path: '/truck-entry'
      fullPath: '/truck-entry/'
      preLoaderRoute: typeof AppTruckEntryIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sales/': {
      id: '/_app/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/truck-entry/new': {
      id: '/_app/truck-entry/new'
      path: '/truck-entry/new'
      fullPath: '/truck-entry/new'
      preLoaderRoute: typeof AppTruckEntryNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sales/new': {
      id: '/_app/sales/new'
      path: '/sales/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof AppSalesNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppSalesNewRoute: typeof AppSalesNewRoute
  AppTruckEntryNewRoute: typeof AppTruckEntryNewRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
  AppTruckEntryIndexRoute: typeof AppTruckEntryIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppSalesNewRoute: AppSalesNewRoute,
  AppTruckEntryNewRoute: AppTruckEntryNewRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
  AppTruckEntryIndexRoute: AppTruckEntryIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
