/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTruckEntryIndexRouteImport } from './routes/_app/truck-entry/index'
import { Route as AppSalesIndexRouteImport } from './routes/_app/sales/index'
import { Route as AppExpensesIndexRouteImport } from './routes/_app/expenses/index'
import { Route as AppCustomerIndexRouteImport } from './routes/_app/customer/index'
import { Route as AppTruckEntryNewRouteImport } from './routes/_app/truck-entry/new'
import { Route as AppSalesNewRouteImport } from './routes/_app/sales/new'
import { Route as AppExpensesNewRouteImport } from './routes/_app/expenses/new'
import { Route as AppCustomerNewRouteImport } from './routes/_app/customer/new'
import { Route as AppTruckEntryEntryIdEditRouteImport } from './routes/_app/truck-entry/$entryId/edit'
import { Route as AppSalesSaleIdEditRouteImport } from './routes/_app/sales/$saleId/edit'
import { Route as AppExpensesExpenseIdEditRouteImport } from './routes/_app/expenses/$expenseId/edit'
import { Route as AppCustomerCustomerIdEditRouteImport } from './routes/_app/customer/$customerId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTruckEntryIndexRoute = AppTruckEntryIndexRouteImport.update({
  id: '/truck-entry/',
  path: '/truck-entry/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExpensesIndexRoute = AppExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomerIndexRoute = AppCustomerIndexRouteImport.update({
  id: '/customer/',
  path: '/customer/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTruckEntryNewRoute = AppTruckEntryNewRouteImport.update({
  id: '/truck-entry/new',
  path: '/truck-entry/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSalesNewRoute = AppSalesNewRouteImport.update({
  id: '/sales/new',
  path: '/sales/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExpensesNewRoute = AppExpensesNewRouteImport.update({
  id: '/expenses/new',
  path: '/expenses/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomerNewRoute = AppCustomerNewRouteImport.update({
  id: '/customer/new',
  path: '/customer/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTruckEntryEntryIdEditRoute =
  AppTruckEntryEntryIdEditRouteImport.update({
    id: '/truck-entry/$entryId/edit',
    path: '/truck-entry/$entryId/edit',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppSalesSaleIdEditRoute = AppSalesSaleIdEditRouteImport.update({
  id: '/sales/$saleId/edit',
  path: '/sales/$saleId/edit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExpensesExpenseIdEditRoute =
  AppExpensesExpenseIdEditRouteImport.update({
    id: '/expenses/$expenseId/edit',
    path: '/expenses/$expenseId/edit',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCustomerCustomerIdEditRoute =
  AppCustomerCustomerIdEditRouteImport.update({
    id: '/customer/$customerId/edit',
    path: '/customer/$customerId/edit',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/customer/new': typeof AppCustomerNewRoute
  '/expenses/new': typeof AppExpensesNewRoute
  '/sales/new': typeof AppSalesNewRoute
  '/truck-entry/new': typeof AppTruckEntryNewRoute
  '/customer/': typeof AppCustomerIndexRoute
  '/expenses/': typeof AppExpensesIndexRoute
  '/sales/': typeof AppSalesIndexRoute
  '/truck-entry/': typeof AppTruckEntryIndexRoute
  '/customer/$customerId/edit': typeof AppCustomerCustomerIdEditRoute
  '/expenses/$expenseId/edit': typeof AppExpensesExpenseIdEditRoute
  '/sales/$saleId/edit': typeof AppSalesSaleIdEditRoute
  '/truck-entry/$entryId/edit': typeof AppTruckEntryEntryIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/customer/new': typeof AppCustomerNewRoute
  '/expenses/new': typeof AppExpensesNewRoute
  '/sales/new': typeof AppSalesNewRoute
  '/truck-entry/new': typeof AppTruckEntryNewRoute
  '/customer': typeof AppCustomerIndexRoute
  '/expenses': typeof AppExpensesIndexRoute
  '/sales': typeof AppSalesIndexRoute
  '/truck-entry': typeof AppTruckEntryIndexRoute
  '/customer/$customerId/edit': typeof AppCustomerCustomerIdEditRoute
  '/expenses/$expenseId/edit': typeof AppExpensesExpenseIdEditRoute
  '/sales/$saleId/edit': typeof AppSalesSaleIdEditRoute
  '/truck-entry/$entryId/edit': typeof AppTruckEntryEntryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/customer/new': typeof AppCustomerNewRoute
  '/_app/expenses/new': typeof AppExpensesNewRoute
  '/_app/sales/new': typeof AppSalesNewRoute
  '/_app/truck-entry/new': typeof AppTruckEntryNewRoute
  '/_app/customer/': typeof AppCustomerIndexRoute
  '/_app/expenses/': typeof AppExpensesIndexRoute
  '/_app/sales/': typeof AppSalesIndexRoute
  '/_app/truck-entry/': typeof AppTruckEntryIndexRoute
  '/_app/customer/$customerId/edit': typeof AppCustomerCustomerIdEditRoute
  '/_app/expenses/$expenseId/edit': typeof AppExpensesExpenseIdEditRoute
  '/_app/sales/$saleId/edit': typeof AppSalesSaleIdEditRoute
  '/_app/truck-entry/$entryId/edit': typeof AppTruckEntryEntryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/customer/new'
    | '/expenses/new'
    | '/sales/new'
    | '/truck-entry/new'
    | '/customer/'
    | '/expenses/'
    | '/sales/'
    | '/truck-entry/'
    | '/customer/$customerId/edit'
    | '/expenses/$expenseId/edit'
    | '/sales/$saleId/edit'
    | '/truck-entry/$entryId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/customer/new'
    | '/expenses/new'
    | '/sales/new'
    | '/truck-entry/new'
    | '/customer'
    | '/expenses'
    | '/sales'
    | '/truck-entry'
    | '/customer/$customerId/edit'
    | '/expenses/$expenseId/edit'
    | '/sales/$saleId/edit'
    | '/truck-entry/$entryId/edit'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/'
    | '/_app/customer/new'
    | '/_app/expenses/new'
    | '/_app/sales/new'
    | '/_app/truck-entry/new'
    | '/_app/customer/'
    | '/_app/expenses/'
    | '/_app/sales/'
    | '/_app/truck-entry/'
    | '/_app/customer/$customerId/edit'
    | '/_app/expenses/$expenseId/edit'
    | '/_app/sales/$saleId/edit'
    | '/_app/truck-entry/$entryId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/truck-entry/': {
      id: '/_app/truck-entry/'
      path: '/truck-entry'
      fullPath: '/truck-entry/'
      preLoaderRoute: typeof AppTruckEntryIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sales/': {
      id: '/_app/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/expenses/': {
      id: '/_app/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AppExpensesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/customer/': {
      id: '/_app/customer/'
      path: '/customer'
      fullPath: '/customer/'
      preLoaderRoute: typeof AppCustomerIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/truck-entry/new': {
      id: '/_app/truck-entry/new'
      path: '/truck-entry/new'
      fullPath: '/truck-entry/new'
      preLoaderRoute: typeof AppTruckEntryNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sales/new': {
      id: '/_app/sales/new'
      path: '/sales/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof AppSalesNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/expenses/new': {
      id: '/_app/expenses/new'
      path: '/expenses/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof AppExpensesNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/customer/new': {
      id: '/_app/customer/new'
      path: '/customer/new'
      fullPath: '/customer/new'
      preLoaderRoute: typeof AppCustomerNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/truck-entry/$entryId/edit': {
      id: '/_app/truck-entry/$entryId/edit'
      path: '/truck-entry/$entryId/edit'
      fullPath: '/truck-entry/$entryId/edit'
      preLoaderRoute: typeof AppTruckEntryEntryIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sales/$saleId/edit': {
      id: '/_app/sales/$saleId/edit'
      path: '/sales/$saleId/edit'
      fullPath: '/sales/$saleId/edit'
      preLoaderRoute: typeof AppSalesSaleIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/expenses/$expenseId/edit': {
      id: '/_app/expenses/$expenseId/edit'
      path: '/expenses/$expenseId/edit'
      fullPath: '/expenses/$expenseId/edit'
      preLoaderRoute: typeof AppExpensesExpenseIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/customer/$customerId/edit': {
      id: '/_app/customer/$customerId/edit'
      path: '/customer/$customerId/edit'
      fullPath: '/customer/$customerId/edit'
      preLoaderRoute: typeof AppCustomerCustomerIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCustomerNewRoute: typeof AppCustomerNewRoute
  AppExpensesNewRoute: typeof AppExpensesNewRoute
  AppSalesNewRoute: typeof AppSalesNewRoute
  AppTruckEntryNewRoute: typeof AppTruckEntryNewRoute
  AppCustomerIndexRoute: typeof AppCustomerIndexRoute
  AppExpensesIndexRoute: typeof AppExpensesIndexRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
  AppTruckEntryIndexRoute: typeof AppTruckEntryIndexRoute
  AppCustomerCustomerIdEditRoute: typeof AppCustomerCustomerIdEditRoute
  AppExpensesExpenseIdEditRoute: typeof AppExpensesExpenseIdEditRoute
  AppSalesSaleIdEditRoute: typeof AppSalesSaleIdEditRoute
  AppTruckEntryEntryIdEditRoute: typeof AppTruckEntryEntryIdEditRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCustomerNewRoute: AppCustomerNewRoute,
  AppExpensesNewRoute: AppExpensesNewRoute,
  AppSalesNewRoute: AppSalesNewRoute,
  AppTruckEntryNewRoute: AppTruckEntryNewRoute,
  AppCustomerIndexRoute: AppCustomerIndexRoute,
  AppExpensesIndexRoute: AppExpensesIndexRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
  AppTruckEntryIndexRoute: AppTruckEntryIndexRoute,
  AppCustomerCustomerIdEditRoute: AppCustomerCustomerIdEditRoute,
  AppExpensesExpenseIdEditRoute: AppExpensesExpenseIdEditRoute,
  AppSalesSaleIdEditRoute: AppSalesSaleIdEditRoute,
  AppTruckEntryEntryIdEditRoute: AppTruckEntryEntryIdEditRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
